title: Computational Physics
description: anferivera's home page editing
theme: just-the-docs

url: https://anferivera.github.io/anferivera

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/anferivera/anferivera
